// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mniak/gomock-contrib/internal/testing (interfaces: GoMockMatcherAndGotFormatter)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGoMockMatcherAndGotFormatter is a mock of GoMockMatcherAndGotFormatter interface.
type MockGoMockMatcherAndGotFormatter struct {
	ctrl     *gomock.Controller
	recorder *MockGoMockMatcherAndGotFormatterMockRecorder
}

// MockGoMockMatcherAndGotFormatterMockRecorder is the mock recorder for MockGoMockMatcherAndGotFormatter.
type MockGoMockMatcherAndGotFormatterMockRecorder struct {
	mock *MockGoMockMatcherAndGotFormatter
}

// NewMockGoMockMatcherAndGotFormatter creates a new mock instance.
func NewMockGoMockMatcherAndGotFormatter(ctrl *gomock.Controller) *MockGoMockMatcherAndGotFormatter {
	mock := &MockGoMockMatcherAndGotFormatter{ctrl: ctrl}
	mock.recorder = &MockGoMockMatcherAndGotFormatterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoMockMatcherAndGotFormatter) EXPECT() *MockGoMockMatcherAndGotFormatterMockRecorder {
	return m.recorder
}

// Got mocks base method.
func (m *MockGoMockMatcherAndGotFormatter) Got(arg0 interface{}) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Got", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// Got indicates an expected call of Got.
func (mr *MockGoMockMatcherAndGotFormatterMockRecorder) Got(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Got", reflect.TypeOf((*MockGoMockMatcherAndGotFormatter)(nil).Got), arg0)
}

// Matches mocks base method.
func (m *MockGoMockMatcherAndGotFormatter) Matches(arg0 interface{}) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Matches", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Matches indicates an expected call of Matches.
func (mr *MockGoMockMatcherAndGotFormatterMockRecorder) Matches(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Matches", reflect.TypeOf((*MockGoMockMatcherAndGotFormatter)(nil).Matches), arg0)
}

// String mocks base method.
func (m *MockGoMockMatcherAndGotFormatter) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockGoMockMatcherAndGotFormatterMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockGoMockMatcherAndGotFormatter)(nil).String))
}
